version: "3.3"

services:
  cache:
    image: redis:6.2-alpine
    restart: always
    ports:
      - "6366:6379"
    command: redis-server --save 20 1 --loglevel warning --requirepass ${REDIS_PASSWORD}
    volumes:
      - ./redis/game-redis-db/:/data
  backend:
    image: game-backend
    restart: always
    ports:
      - "5005:5005"
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
