version: "3.3"

services:
  cache:
    image: redis:6.2-alpine
    restart: always
    ports:
      - "6366:6379"
    command: redis-server --save 20 1 --loglevel warning --requirepass ${REDIS_PASSWORD}
    volumes:
      - ./game-redis-db/:/data
