name: Deploy robot party website

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v2

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.ROBOTS_DEPLOY_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.ROBOTS_DEPLOY_SECRET_ACCESS_KEY }}
          aws-region: ap-southeast-1

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install yarn
        working-directory: ./frontend
        run: npm install --global yarn

      - name: Install dependencies
        working-directory: ./frontend
        run: yarn install

      - name: Build app
        working-directory: ./frontend
        run: yarn build

      - name: Copy public files into dist directory
        working-directory: ./frontend
        run: cp distfiles/*.* dist/

      - name: Deploy static site to S3 bucket
        working-directory: ./frontend
        run: aws s3 sync ./dist/ s3://${{ secrets.ROBOTS_BUCKET_NAME }}

      - name: Invalidate CloudFront
        uses: chetan/invalidate-cloudfront-action@v2
        env:
          DISTRIBUTION: ${{ secrets.ROBOTS_DISTRIBUTION }}
          PATHS: "/*"
          AWS_REGION: "us-east-1"
          AWS_ACCESS_KEY_ID: ${{ secrets.ROBOTS_DEPLOY_ACCESS_KEY }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.ROBOTS_DEPLOY_SECRET_ACCESS_KEY }}
